ClubManagement/Models/Match.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ClubManagement.Models
{
    public class Match
    {
        [Key]
        public int Id { get; set; }
        public int? MainCoachId { get; set; }
        public string Enemy { get; set; } = string.Empty;
        public string? Place { get; set; }
        public string AgeCategory { get; set; } = string.Empty;
        public DateTime? DateOfMatch {  get; set; }
        public DateTime? StartMatch { get; set; }
        public string? Score { get; set; }
        public string? ScoreStatus { get; set; }
        public string MatchHost { get; set; } = string.Empty;
        public string MatchStatus {  get; set; } = string.Empty;
        public string TypeOfMatch {  get; set; } = string.Empty;

        // Footballer *-* Match
        public ICollection<Footballer> Footballers { get; set; } = new List<Footballer>();

        // Relacja jeden do jeden z StartingEleven
        public ICollection<PrimaryMatchPlayer> PrimaryMatchPlayers { get; set; } = new List<PrimaryMatchPlayer>();
        public ICollection<SubstituteMatchPlayer> SubstituteMatchPlayers { get; set; } = new List<SubstituteMatchPlayer>();

        // Coach 1-* Match
        public Coach? MainCoach { get; set; }
    }
}

ClubManagement/Models/MatchResult.cs
namespace ClubManagement.Models
{
    public class MatchResult
    {
        public int Id { get; set; }
        public int? HomeTeamScore { get; set; }
        public int? AwayTeamScore { get; set; }

        public MatchResult(int homeTeamScore, int awayTeamScore)
        {
            HomeTeamScore = homeTeamScore;
            AwayTeamScore = awayTeamScore;
        }

        public override string ToString()
        {
            return $"{HomeTeamScore}-{AwayTeamScore}";
        }
    }
}

ClubManagement/Controllers/MatchController.cs
using ClubManagement.ApplicationDbContext;
using ClubManagement.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace ClubManagement.Controllers
{
    public class MatchController : Controller
    {
        private readonly ClubDbContext _context;
        public MatchController(ClubDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        //[Authorize(Policy = "")]
        public IActionResult ShowMatches(string? filterCategory = "firstTeam")
        {
            ViewBag.FilterCategory = filterCategory;

            IQueryable<Match> m = _context.Matches
                   .Where(m => m.AgeCategory == filterCategory)
                   .OrderBy(m => m.DateOfMatch);

            return View(m);
        }

        [HttpGet]
        //[Authorize(Policy = "")]
        public IActionResult MatchSchedule()
        {
            var currentTime = DateTime.Now;
            var match = _context.Matches.Where(m => m.StartMatch > currentTime).ToList();

            return View(match);
        }

        [HttpGet]
        //[Authorize(Policy = "")]
        public IActionResult MatchResults()
        {
            var currentTime = DateTime.Now;
            var obj = _context.Matches.Where(m => m.StartMatch < currentTime).ToList();

            return View(obj);
        }

        [HttpGet]
        //[Authorize(Policy = "")]
        public IActionResult MatchDetails(int? id)
        {
            if (id == null || id == 0)
                return NotFound("Brak ID meczu.");

            var match = _context.Matches
                            .Include(m => m.MainCoach)
                            .Include(m => m.PrimaryMatchPlayers)
                                .ThenInclude(p => p.Footballer)
                            .Include(m => m.SubstituteMatchPlayers)
                                .ThenInclude(s => s.Footballer)
                            .FirstOrDefault(m => m.Id == id);

            if (match == null)
                return NotFound("Mecz nie istnieje.");

            return View(match);
        }

        [HttpGet]
        public IActionResult LastMatchesWithOpponent(string? opponentName)
        {
            if(opponentName == null || opponentName == "")
                return NotFound();

            // Pobierz ostatnie mecze z danym przeciwnikiem
            var lastMatches = _context.Matches
                .Where(m => m.Enemy == opponentName)
                .OrderByDescending(m => m.DateOfMatch)
                .Take(10) // Wybierz 10 ostatnich meczów
                .ToList();

            ViewBag.OpponentName = opponentName;

            return View(lastMatches);
        }

        /////////////////////
        [HttpGet]
        //[Authorize(Policy = "")]
        public IActionResult PrepareToAddMatch(string? filterCategory = "firstTeam")
        {
            ViewBag.FilterCategory = filterCategory;
            return View();
        }

        [HttpPost]
        //[Authorize(Policy = "")]
        public IActionResult AddMatch([FromForm]Match m, [FromForm] List<int> selectedPlayers)
        {
            // Sprawdzenie czy podane data i czas nie są wcześniejsze niż chwila obecna
            if(m.DateOfMatch != null)
            {
                DateTime now = DateTime.Now;

                if (m.DateOfMatch.Value.Date < now.Date ||
                    (m.DateOfMatch.Value.Date == now.Date && m.StartMatch.Value.TimeOfDay < now.TimeOfDay))
                {
                    TempData["Alert"] = "Data lub godzina rozpoczęcia jest wcześniejsza niż obecna chwila";
                    return RedirectToAction("PrepareToAddMatch", new { filterCategory = m.AgeCategory });
                }
            }


            _context.Matches.Add(m);

            _context.SaveChanges();
            TempData["Success"] = "Pomyslnie dodano trening";

            return RedirectToAction("ShowMatches", new { filterCategory = m.AgeCategory });
        }

        [HttpGet]
        //[Authorize(Policy = "")]
        public IActionResult PrepareToEditMatch(int? id)
        {
            if (id == null || id == 0)
                return NotFound("PrepareToEditMatch - nie ma id ");

            var obj = _context.Matches.FirstOrDefault(x => x.Id == id);

            if (obj == null)
                return NotFound("PrepareToEditMatch - nie ma obj w bazie danych");

            return View(obj);
        }

        [HttpPost]
        //[Authorize(Policy = "")]
        public IActionResult EditMatch([FromForm] Match m, int? TeamGoals, int? OpponentGoals)
        {
            // Sprawdzenie czy podane data i czas nie są wcześniejsze niż chwila obecna
            if (m.DateOfMatch != null)
            {
                DateTime now = DateTime.Now;

                if ((m.MatchStatus == "coming" || m.MatchStatus == "canceled" || m.MatchStatus == "delayed") &&
                    (m.DateOfMatch.Value.Date < now.Date ||
                    (m.DateOfMatch.Value.Date == now.Date && (m.StartMatch != null && m.StartMatch.Value.TimeOfDay < now.TimeOfDay))))
                {
                    TempData["Alert"] = "Jeśli mecz jest nadchodzący lub przełożony, data lub godzina rozpoczęcia musi być wcześniejsza niż obecna chwila";
                    return RedirectToAction("PrepareToEditMatch", new { id = m.Id });
                }

                if (m.MatchStatus == "finished" &&
                    (m.DateOfMatch.Value.Date > now.Date ||
                    (m.DateOfMatch.Value.Date == now.Date && (m.StartMatch != null && m.StartMatch.Value.TimeOfDay > now.TimeOfDay))))
                {
                    TempData["Alert"] = "Jeśli mecz jest skończony, data lub godzina rozpoczęcia musi być wcześniejsza niż obecna chwila";
                    return RedirectToAction("PrepareToEditMatch", new { id = m.Id });
                }
            }

            // walidacja do wyniku
            if (TeamGoals != null && OpponentGoals != null)
            {
                if (TeamGoals < 0 || OpponentGoals < 0)
                {
                    TempData["Alert"] = "Żle podałeś wyniki drużyn nie mogą być mniejsze niż 0";
                    return RedirectToAction("PrepareToEditMatch", new { id = m.Id });
                }

                string score;
                string scoreStatus;

                if (TeamGoals > OpponentGoals)
                    scoreStatus = "win";
                else if (TeamGoals < OpponentGoals)
                    scoreStatus = "loss";
                else
                    scoreStatus = "draw";

                if (m.MatchHost == "home")
                    score = $"{TeamGoals} - {OpponentGoals}";
                else
                    score = $"{OpponentGoals} - {TeamGoals}";

                m.Score = score;
                m.ScoreStatus = scoreStatus;
            }


            _context.Matches.Update(m);

            _context.SaveChanges();
            TempData["Success"] = "Pomyslnie zedytowano trening trening";

            return RedirectToAction("ShowMatches", new { filterCategory = m.AgeCategory });
        }

        [HttpGet]
        public IActionResult RemoveMatch(int? id)
        {
            if (id == null || id == 0)
                return NotFound("RemoveMatch - nie ma id");

            var obj = _context.Matches.FirstOrDefault(gt => gt.Id == id);

            if (obj == null)
                return NotFound("RemoveGT - Nie znaleziono obiektu");

            _context.Matches.Remove(obj);
            _context.SaveChanges();

            return RedirectToAction("ShowMatches", new { filterCategory = obj.AgeCategory });
        }

        [HttpGet]
        //[Authorize(Policy = "")]
        public IActionResult PrepareToAddTrainer(int? id)
        {
            if (id == null || id == 0)
                return NotFound("PrepareToAddStaff - brak id");

            var obj = _context.Matches.FirstOrDefault(m => m.Id == id);

            if (obj == null)
                return NotFound("PrepareToAddTrainer - brak obj w bazie danych");

            ViewBag.Coaches = _context.Coaches;

            return View(obj);
        }

        [HttpPost]
        //[Authorize(Policy = "")]
        public IActionResult AddTrainer([FromForm]Match match)
        {
            var obj = _context.Matches.FirstOrDefault(m => m.Id == match.Id);
            if (obj == null)
                return NotFound("AddTrainer - nie ma w bazie");

            obj.MainCoachId = match.MainCoachId;
            
            _context.SaveChanges();

            return RedirectToAction("ShowMatches", new { filterCategory = obj.AgeCategory });
        }

        [HttpGet]
        //[Authorize(Policy = "")]
        public IActionResult PrepareToAddStaff(int? id)
        {
            if (id == null || id == 0)
                return NotFound("Brak ID meczu.");

            var match = _context.Matches.FirstOrDefault(m => m.Id == id);

            if (match == null)
                return NotFound("SAdas");

            var primaryPlayers = _context.PrimaryMatchPlayers
                                .Where(p => p.MatchId == match.Id)
                                .Select(p => p.FootballerId)
                                .ToList();

            // Pobranie piłkarzy należących do rezerw
            var substitutePlayers = _context.SubstituteMatchPlayers
                                            .Where(s => s.MatchId == match.Id)
                                            .Select(s => s.FootballerId)
                                            .ToList();


            ViewBag.Players = _context.Footballers.Where(f => f.AgeCategory == match.AgeCategory);
            ViewBag.PrimaryPlayers = primaryPlayers;
            ViewBag.SubstitutePlayers = substitutePlayers;

            return View(match);
        }

        [HttpPost]
        //[Authorize(Policy = "")]

ClubManagement/Views/Match/LastMatchesWithOpponent.cshtml
@model IEnumerable<Match>

<h2>Ostatnie mecze z @ViewBag.OpponentName</h2>

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Numer</th>
                <th>Przeciwnik</th>
                <th>Miejsce</th>
                <th>Data meczu</th>
                <th>Godzina rozpoczęcia</th>
                <th>Wynik</th>
                <th>Status</th>
                <th>Typ</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var match in Model)
            {
                <tr>
                    <td>@match.Id</td>
                    <td>@match.Enemy</td>
                    <td>@match.Place</td>
                    <td>@match.DateOfMatch.Value.ToString("dd/MM/yyyy")</td>
                    <td>@match.StartMatch.Value.ToString("HH:mm")</td>
                    <td>@match.Score</td>
                    <td>@match.MatchStatus</td>
                    <td>@match.TypeOfMatch</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Brak danych o meczach z @ViewBag.OpponentName.</p>
}

ClubManagement/Views/Match/MatchDetails.cshtml
@model Match;

<h1>Detale meczu</h1>

<p><a asp-controller="Match" asp-action="LastMatchesWithOpponent" asp-route-opponentName="@Model.Enemy">Ostatnie mecze z przeciwko temu zespołowi</a></p>

<p>ID meczu: @Model.Id</p>
<p>Wróg: @Model.Enemy</p>
<p>Miejsce: @Model.Place</p>
<p>Kategoria wiekowa: @Model.AgeCategory</p>
<p>Data meczu: @Model.DateOfMatch</p>
<p>Godzina rozpoczęcia: @Model.StartMatch</p>
<p>Wynik: @Model.Score</p>
<p>Status meczu: @Model.MatchStatus</p>
<p>Gospodarz meczu: @Model.MatchHost</p>
<p>Rodzaj meczu: @Model.TypeOfMatch</p>

@if(@Model.MainCoach != null)
{
    <h2>Trener</h2>
    <p>@Model.MainCoach.Name</p>
}
else
{
    <p>Brak wpisanego trenera</p>
}

<h2>Podstawowa jedenastka</h2>
<ul>
@foreach (var player in Model.PrimaryMatchPlayers)
{
    <li>@player.Footballer.Name @player.Footballer.LastName</li>
}
</ul>

<h2>Rezerwa</h2>
<ul>
@foreach (var player in Model.SubstituteMatchPlayers)
{
    <li>@player.Footballer.Name @player.Footballer.LastName</li>
}
</ul>

ClubManagement/Views/Match/MatchResults.cshtml
@model IEnumerable<Match>

<h2>Zakończone mecze</h2>

@if (Model.Any())
{
    <ul>
        @foreach (var match in Model)
        {
            <li>
                @match.Enemy - @(string.IsNullOrEmpty(match.Score) ? "Brak wyniku" : match.Score)
            </li>
        }
    </ul>
}
else
{
    <p>Brak wyników meczów.</p>
}

ClubManagement/Views/Match/MatchSchedule.cshtml
@model IEnumerable<Match>

<h2>Przyszłe mecze</h2>

@if (Model.Any())
{
    <ul>
        @foreach (var match in Model)
        {
            <li>
                @match.Enemy - @(string.IsNullOrEmpty(match.Score) ? "Brak wyniku" : match.Score)
            </li>
        }
    </ul>
}
else
{
    <p>Brak wyników meczów.</p>
}

ClubManagement/Views/Match/PrepareToAddMatch.cshtml
@model Match;

<style>
    button, .fields {
        display: block;
    }
</style>

@if(TempData["Success"] != null)
{
    <div class="alert alert-success">
        @TempData["Success"]
    </div>
}
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}

<div>
    <h2>Dodawanie nowego meczu</h2>
    <p>
        <a asp-controller="Match" asp-action="showMatches" asp-route-filterCategory="@ViewBag.FilterCategory">
            Powrót
        </a>
    </p>
</div>

@* <div>
    <form method="get" asp-action="PrepareToAddMatch">
        <label>Wybierz pozycje zawodników do dodania</label>
        <select name="filterPosition">
            <option value="all" selected="@(ViewBag.FilterPosition == "all" ? true : false)">Wszyscy</option>
            <option value="goalkeeper" selected="@(ViewBag.FilterPosition == "goalkeeper" ? true : false)">Bramkarze</option>
            <option value="defender" selected="@(ViewBag.FilterPosition == "defender" ? true : false)">Obrońcy</option>
            <option value="helper" selected="@(ViewBag.FilterPosition == "helper" ? true : false)">Pomocnicy</option>
            <option value="attacker" selected="@(ViewBag.FilterPosition == "attacker" ? true : false)">Napastnicy</option>
        </select>

        <input type="hidden" name="filterCategory" value="@ViewBag.FilterCategory" />

        <button type="submit">Filtruj zawodników</button>
    </form>
</div>
 *@
<div>
    <form method="post" asp-action="AddMatch">

        <button type="submit">Dodaj mecz</button>

        <div class="fields">
            <label asp-for="Enemy">Pzeciwnik</label>
            <input type="text" asp-for="Enemy" />
        </div>
        <div class="fields">
            <label asp-for="Place">Miejsce spotkania</label>
            <input type="text" asp-for="Place" />
        </div>
        <div class="fields">
            <label asp-for="DateOfMatch">Data meczu</label>
            <input type="date" asp-for="DateOfMatch" />
        </div>
        <div class="fields">
            <label asp-for="StartMatch">Godzina rozpoczęcia</label>
            <input type="time" asp-for="StartMatch" />
        </div>

        <div>
            <label asp-for="AgeCategory">Kategoria wiekowa:</label>
            <select asp-for="AgeCategory">
                <option value="firstTeam">Seniorzy</option>
                <option value="reserves">Rezerwa</option>
                <option value="juniors">Juniorzy</option>
            </select>
        </div>
        
        <div>
            <label>Status meczu</label>
            <select asp-for="MatchStatus">
                <option value="coming">Nadchodzący</option>
            </select>
        </div>

        <div>
            <label>Typ spotkania</label>
            <select asp-for="TypeOfMatch">
                <option value="league">Ligowy</option>
                <option value="cup">Pucharowy</option>
                <option value="friendly">Towarzyski</option>
            </select>
        </div>

        <div>
            <label>Gospodarz meczu:</label>
            <select asp-for="MatchHost">
                <option value="home">Domowy</option>
                <option value="away">Wyjazdowy</option>
            </select>
        </div>

    </form>
</div>

ClubManagement/Views/Match/PrepareToAddStaff.cshtml
@model Match;

<style>
    button, .fields {
        display: block;
    }
</style>

<div>
    <p>Dodaj podstawową 11 do meczu</p>
    <p><a asp-controller="Match" asp-action="ShowMatches" asp-route-filterCategory="@Model.AgeCategory">Powrót</a></p>
    <p><a asp-controller="Match" asp-action="ClearMatchPlayers" asp-route-id="@Model.Id">Usuń skłąd do meczu</a></p>
</div>
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}
<form method="post" asp-action="AddStaff">
    <button type="submit">Dodaj</button>

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>Piłkarze</label>
        @foreach (var footballer in ViewBag.Players)
        {
            bool isPrimaryPlayer = ViewBag.PrimaryPlayers.Contains(footballer.Id);
            bool isSubstitutePlayer = ViewBag.SubstitutePlayers.Contains(footballer.Id);

            <div>

                <label >@footballer.Name @footballer.LastName - @footballer.Position (@footballer.AgeCategory)</label>:
                <input type="checkbox" name="selectedElevenPlayers" value="@footballer.Id" id="eleven_@footballer.Id" checked="@isPrimaryPlayer" /> - <label for="eleven_@footballer.Id">Podstawowa 11</label> |
                <input type="checkbox" name="selectedSubstitutePlayers" value="@footballer.Id" id="substitute_@footballer.Id" checked="@isSubstitutePlayer" /> - <label for="substitute_@footballer.Id">Rezerwa</label>
            </div>
        }
    </div>

</form>
<script>
    // Funkcja, która odznaczy checkbox przy podstawowej jedenastce, gdy zostanie zaznaczony checkbox przy rezerwie i vice versa
    document.querySelectorAll('input[type="checkbox"]').forEach(function (checkbox) {
        checkbox.addEventListener('change', function () {
            if (this.name === 'selectedElevenPlayers') {
                var substituteCheckbox = document.getElementById('substitute_' + this.value);
                if (substituteCheckbox.checked) {
                    substituteCheckbox.checked = false;
                }
            } else if (this.name === 'selectedSubstitutePlayers') {
                var elevenCheckbox = document.getElementById('eleven_' + this.value);
                if (elevenCheckbox.checked) {
                    elevenCheckbox.checked = false;
                }
            }
        });
    });
</script>

ClubManagement/Views/Match/PrepareToAddTrainer.cshtml
@model Match;

<style>
    button, .fields {
        display: block;
    }
</style>

<div>
    <p>Dodaj zawodników do meczu</p>
    <p><a asp-controller="Match" asp-action="ShowMatches" asp-route-filterCategory="@Model.AgeCategory">Powrót</a></p>
</div>
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}
<form method="post" asp-action="AddTrainer">
    <button type="submit">Dodaj trenera do meczu</button>

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>Trenerzy</label>
        <div>
            <input type="radio" asp-for="MainCoachId" value="" checked="@(Model.MainCoachId == null ? true : false)" />
            <label asp-for="MainCoachId">Brak trenera</label>
        </div>
        @foreach (var coach in ViewBag.Coaches)
        {
            <div>
                <input type="radio" asp-for="MainCoachId" value="@coach.Id" id="@($"{coach.Id}")" checked="@(Model.MainCoachId == coach.Id ? true : false)" />
                <label for="@($"{coach.Id}")">@coach.Name @coach.LastName - @coach.KindOfCoach</label>
            </div>
        }
    </div>
</form>

ClubManagement/Views/Match/PrepareToEditMatch.cshtml
@model Match;

@{
    string teamScore = "";
    string opponentScore = "";
    if(Model.Score != null)
    {
        if(Model.MatchHost == "home")
        {
            teamScore = Model.Score.Split("-")[0].Trim();
            opponentScore = Model.Score.Split("-")[1].Trim();
        }
        else
        {
            teamScore = Model.Score.Split("-")[1].Trim();
            opponentScore = Model.Score.Split("-")[0].Trim();

        }
    }
}

<style>
    button, .fields {
        display: block;
    }
</style>

@if (TempData["Success"] != null)
{
    <div class="alert alert-success">
        @TempData["Success"]
    </div>
}
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}

<div>
    <h2>Edytowanie meczu</h2>
    <p>
        <a asp-controller="Match" asp-action="showMatches" asp-route-filterCategory="@Model.AgeCategory">
            Powrót
        </a>
    </p>
</div>

 
<div>
    <form method="post" asp-action="EditMatch">

        <button type="submit">Edytuj mecz</button>

        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="MainCoachId" />

        <div class="fields">
            <label asp-for="Enemy">Pzeciwnik</label>
            <input type="text" asp-for="Enemy" />
        </div>
        <div class="fields">
            <label asp-for="Place">Miejsce spotkania</label>
            <input type="text" asp-for="Place" />
        </div>
        <div class="fields">
            <label asp-for="DateOfMatch">Data meczu</label>
            <input type="date" asp-for="DateOfMatch" />
        </div>
        <div class="fields">
            <label asp-for="StartMatch">Godzina rozpoczęcia</label>
            <input type="time" asp-for="StartMatch" />
        </div>

        <div class="fields">
            <label name="TeamGoals">Gole drużyny</label>
            <input type="number" name="TeamGoals" value="@teamScore" />
        </div>
        <div class="fields">
            <label name="OpponentGoals">Gole przeciwnika</label>
            <input type="number" name="OpponentGoals" value="@opponentScore" />
        </div>

        <div>
            @{
                string chosenCategory;
                if (Model.AgeCategory == "firstTeam")
                    chosenCategory = "Seniorz";
                else if (Model.AgeCategory == "firstTeam")
                    chosenCategory = "Rezerwa";
                else
                    chosenCategory = "Juniorzy";
            }
            <label asp-for="AgeCategory">Kategoria wiekowa:</label>
            <select asp-for="AgeCategory">
                <option value="@Model.AgeCategory">@chosenCategory</option>
            </select>
        </div>

        <div>
            <label>Status meczu</label>
            <select asp-for="MatchStatus">
                <option value="coming">Nadchodzący</option>
                <option value="finished">Zakończony</option>
                <option value="canceled">Odwołany</option>
                <option value="delayed">Przełożony</option>
            </select>
        </div>

        <div>
            @{
                string chosenType;
                if (Model.TypeOfMatch == "league")
                    chosenType = "Ligowy";
                else if (Model.TypeOfMatch == "cup")
                    chosenType = "Pucharowy";
                else
                    chosenType = "Towarzyski";
            }
            <label>Typ spotkania</label>
            <select asp-for="TypeOfMatch">
                <option value="@Model.TypeOfMatch">@chosenType</option>
            </select>
        </div>

        <div>
            <label>Gospodarz meczu:</label>
            <select asp-for="MatchHost">
                <option value="home">Domowy</option>
                <option value="away">Wyjazdowy</option>
            </select>
        </div>

    </form>
</div>

ClubManagement/Views/Match/ShowMatches.cshtml
@model IQueryable<Match>;

<div>
    <h1>Mecze </h1>
    <p><a asp-controller="home" asp-action="index">Powrót</a></p>
    <p>
        <a asp-controller="Match" asp-action="PrepareToAddMatch" asp-route-filterCategory="@ViewBag.FilterCategory">
            Dodaj mecz
        </a>
    </p>
    <p><a asp-controller="Match" asp-action="MatchResults">Pokaż poprzednie mecze</a></p>
    <p><a asp-controller="Match" asp-action="MatchSchedule">Pokaż harmonogram meczy</a></p>
    
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success">
            @TempData["Success"]
        </div>
    }
    @if (TempData["Alert"] != null)
    {
        <div class="alert alert-danger ">
            @TempData["Alert"]
        </div>
    }
    <div>
        <form method="get" asp-action="ShowMatches">
            <div>
                <div>
                    <label>Kategoria wiekowa</label>
                    <select name="filterCategory">
                        <option value="firstTeam" selected="@(ViewBag.FilterCategory == "firstTeam" ? true : false)">Seniorzy</option>
                        <option value="reserves" selected="@(ViewBag.FilterCategory == "reserves" ? true : false)">Rezerwy</option>
                        <option value="juniors" selected="@(ViewBag.FilterCategory == "juniors" ? true : false)">Juniorzy</option>
                        @* <option value="all" selected="@(ViewBag.FilterCategory == "all" ? true : false)">Treningi dla wszystkich</option> *@
                    </select>
                </div>

                <button type="submit">Filtruj</button>
            </div>
        </form>
    </div>

    <div>
        @foreach (var obj in Model)
        {
            <div>@obj.TypeOfMatch</div>
            <div>
                @obj.Enemy - 
                @((obj.DateOfMatch != null) ? obj.DateOfMatch.Value.ToString("dd-MM-yyyy") : "Brak okreslonego dnia") |
                @if (obj.MatchStatus == "canceled" || obj.MatchStatus == "delayed")
                {
                    @obj.MatchStatus
                }
                else
                {
                    @((obj.StartMatch != null) ? obj.StartMatch.Value.ToString("HH:mm") : "Brak okreslonej godziny")
                }
                <a asp-controller="Match" asp-action="MatchDetails" asp-route-id="@obj.Id">Szczegóły</a> |
                <a asp-controller="Match" asp-action="PrepareToEditMatch" asp-route-id="@obj.Id" asp-route-filterCategory="@ViewBag.FilterCategory">Edytuj</a> |
                <a asp-controller="Match" asp-action="PrepareToAddTrainer" asp-route-id="@obj.Id">Trener</a> |
                <a asp-controller="Match" asp-action="PrepareToAddStaff" asp-route-id="@obj.Id">Ustal skład</a> |
                <a asp-controller="Match" asp-action="RemoveMatch" asp-route-id="@obj.Id" asp-route-filterCategory="@ViewBag.FilterCategory">Usuń</a>
            </div>
        }
    </div>

</div>