ClubManagement/Models/IndividualTraining.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ClubManagement.Models
{
    public class IndividualTraining
    {
        [Key]
        public int Id { get; set; }
        public int FootballerId { get; set; }
        public int? CoachId { get; set; }
        public string Type { get; set; } = "Indywidualny";
        public DateTime DateOfTraining { get; set; }
        public DateTime StartTraining { get; set; }
        public DateTime EndTraining { get; set; }
        public TimeSpan TimeOfTraining { get; set; }
        public string Title { get; set; } = string.Empty;
        public string? Description { get; set; }
        public string? Place {  get; set; }
        //public ICollection<Exercise> Exercises { get; set; } = new List<Exercise>();

        // Footballer 1-* IndividualTraining 
        public Footballer Footballer { get; set; }
        // Coach 1-* IndividualTraining 
        public Coach? Coach { get; set; }
    }
}

ClubManagement/Controllers/IndividualTrainingController.cs
using ClubManagement.ApplicationDbContext;
using ClubManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace ClubManagement.Controllers
{
    public class IndividualTrainingController : Controller
    {
        private readonly ClubDbContext _context;
        public IndividualTrainingController(ClubDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult ShowPlayers()
        {
            IEnumerable<Footballer> footballers = _context.Footballers;
            return View(footballers);
        }

        [HttpGet]
        public IActionResult ShowIT(int? id)
        {
            if(id == null || id == 0)
                return NotFound();

            var obj = _context.Footballers.Include(f => f.IndividualTrainings)
                .ThenInclude(it => it.Coach) // Włącz dane o trenerach
                .FirstOrDefault(x => x.Id == id);

            if(obj == null)
                return NotFound();

            return View(obj);
        }

        // Dodawanie
        [HttpGet]
        public IActionResult PrepareToAddIT(int? id)
        {
            if(id == null || id == 0)
                return NotFound();

            IQueryable<Coach> coaches = _context.Coaches;           

            ViewBag.FootballerId = id;
            ViewBag.Coaches = coaches;

            return View();
        }

        [HttpPost]
        public IActionResult AddIT([FromForm]IndividualTraining it)
        {
            // Sprawdzenie czy podane data i czas nie są wcześniejsze niż chwila obecna
            DateTime now = DateTime.Now;

            if (it.DateOfTraining.Date < now.Date ||
                (it.DateOfTraining.Date == now.Date && it.StartTraining.TimeOfDay < now.TimeOfDay))
            {
                TempData["Alert"] = "Data lub godzina rozpoczęcia jest wcześniejsza niż obecna chwila";
                return RedirectToAction("PrepareToAddIT", new { id = it.FootballerId });
            }

            it.StartTraining = it.DateOfTraining.Date + it.StartTraining.TimeOfDay;
            it.EndTraining = it.DateOfTraining.Date + it.EndTraining.TimeOfDay;

            if (it.EndTraining < it.StartTraining)
            {
                TempData["Alert"] = "Zakończenie treningu jest wcześniej niż rozpoczęcie";
                return RedirectToAction("PrepareToAddIT", new { id = it.FootballerId });
            }

            it.TimeOfTraining = it.EndTraining - it.StartTraining;

            _context.IndividualTraining.Add(it);
            _context.SaveChanges();

            TempData["Success"] = "Pomyslnie dodano trening";
            return RedirectToAction("ShowIT", new { id = it.FootballerId });
        }

        // Edytowanie
        public IActionResult PrepareToEditIT(int? id)
        {
            if(id  == null || id == 0)
                return NotFound();

            var obj = _context.IndividualTraining.FirstOrDefault(it => it.Id == id);

            if (obj == null) 
                return NotFound();

            ViewBag.Coaches = _context.Coaches;

            return View(obj);
        }

        public IActionResult EditIT([FromForm]IndividualTraining it) 
        {
            // Sprawdzenie czy podane data i czas nie są wcześniejsze niż chwila obecna
            DateTime now = DateTime.Now;

            if (it.DateOfTraining.Date < now.Date ||
                (it.DateOfTraining.Date == now.Date && it.StartTraining.TimeOfDay < now.TimeOfDay))
            {
                TempData["Alert"] = "Data,godzina rozpoczęcia lub zakończenia treningu jest wcześniejsza niż obecna chwila";
                return RedirectToAction("PrepareToEditIT", new { id = it.Id });
            }

            it.StartTraining = it.DateOfTraining.Date + it.StartTraining.TimeOfDay;
            it.EndTraining = it.DateOfTraining.Date + it.EndTraining.TimeOfDay;

            if (it.EndTraining < it.StartTraining)
            {
                TempData["Alert"] = "Zakończenie treningu jest wcześniej niż rozpoczęcie";
                return RedirectToAction("PrepareToEditIT", new { id = it.Id });
            }

            it.TimeOfTraining = it.EndTraining - it.StartTraining;

            _context.IndividualTraining.Update(it);
            _context.SaveChanges();

            return RedirectToAction("ShowIT", new { id = it.FootballerId});
        }
        // Usuwanie
        public IActionResult RemoveIT(int? id)
        {
            if(id == null || id == 0)
                return NotFound();

            var obj = _context.IndividualTraining.FirstOrDefault(x => x.Id == id);

            if (obj == null)
                return NotFound();

            int footballerId = obj.FootballerId;

            _context.IndividualTraining.Remove(obj);
            _context.SaveChanges();

            return RedirectToAction("ShowIT", new { id = footballerId });
        }

        public IActionResult RemoveAllIT(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            // Znajdź wszystkie treningi dla danego FootballerId
            var trainingsToRemove = _context.IndividualTraining.Where(x => x.FootballerId == id).ToList();

            if (trainingsToRemove == null || trainingsToRemove.Count == 0)
                return NotFound();

            int footballerId = trainingsToRemove.First().FootballerId;

            // Usuń wszystkie znalezione treningi
            _context.IndividualTraining.RemoveRange(trainingsToRemove);
            _context.SaveChanges();

            return RedirectToAction("ShowIT", new { id = footballerId });
        }
    }
}

ClubManagement/Views/IndividualTraining/PrepareToAddIT.cshtml
@model IndividualTraining;

<style>
    button, .fields {
        display: block;
    }
</style>

<div>
    <p>Dodaj indywidualny trening</p>
    <p><a asp-controller="IndividualTraining" asp-action="ShowIT" asp-route-id="@ViewBag.FootballerId">Powrót</a></p>
</div>
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}
<form method="post" asp-action="AddIT">
    <input type="hidden" asp-for="FootballerId" value="@ViewBag.FootballerId" />
    <div class="fields">
        <label asp-for="Title">Tytuł</label>
        <input type="text" asp-for="Title" />
    </div>
    <div class="fields">
        <label asp-for="Description">Opis</label>
        <input type="text" asp-for="Description" />
    </div>
    <div class="fields">
        <label asp-for="Place">Miejsce</label>
        <input type="text" asp-for="Place" />
    </div>
    <div class="fields">
        <label asp-for="DateOfTraining">Data treningu</label>
        <input type="date" asp-for="DateOfTraining" />
    </div>
    <div class="fields">
        <label asp-for="StartTraining">Godzina rozpoczęcia</label>
        <input type="time" asp-for="StartTraining" />
    </div>
    <div class="fields">
        <label asp-for="EndTraining">Godzina zakończenia</label>
        <input type="time" asp-for="EndTraining" />
    </div>
    <div class="form-group">
        <label>Trenerzy</label>
        <div>
            <input type="radio" asp-for="CoachId" value="" checked/>
            <label asp-for="CoachId">Brak trenera</label>
        </div>
        @foreach (var coach in ViewBag.Coaches)
        {
            <div>
                <input type="radio" asp-for="CoachId" value="@coach.Id" id="@($"{coach.Id}")" />
                <label for="@($"{coach.Id}")">@coach.Name @coach.LastName - @coach.KindOfCoach</label>
            </div>
        } 
    </div>
    <button type="submit">
        Dodaj Trening
    </button>
</form>

ClubManagement/Views/IndividualTraining/PrepareToEditIT.cshtml
@model IndividualTraining;

<style>
    button, .fields {
        display: block;
    }
</style>
<div>
    <h1>Edycja indywidualnego treningu</h1>
    <p><a asp-controller="IndividualTraining" asp-action="ShowIT" asp-route-id="@Model.FootballerId">Powrót</a></p>
</div>
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}
<form method="post" asp-action="EditIT">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="FootballerId" />

    <div class="fields">
        <label asp-for="Title">Tytuł</label>
        <input type="text" asp-for="Title" />
    </div>

    <div class="fields">
        <label asp-for="Description">Opis</label>
        <input type="text" asp-for="Description" />
    </div>

    <div class="fields">
        <label asp-for="Place">Miejsce</label>
        <input type="text" asp-for="Place" />
    </div>

    <div class="fields">
        <label asp-for="DateOfTraining">Data treningu</label>
        <input type="date" asp-for="DateOfTraining" />
    </div>

    <div class="fields">
        <label asp-for="StartTraining">Start treningu</label>
        <input type="time" asp-for="StartTraining" />
    </div>

    <div class="fields">
        <label asp-for="EndTraining">Koniec treningu</label>
        <input type="time" asp-for="EndTraining" />
    </div>
    <div class="form-group">
        <label>Trenerzy</label>
        <div>
            <input type="radio" asp-for="CoachId" value="" checked="@(Model.CoachId == null ? true : false)" />
            <label asp-for="CoachId">Brak trenera</label>
        </div>
        @foreach (var coach in ViewBag.Coaches)
        {
            <div>
                <input type="radio" asp-for="CoachId" value="@coach.Id" id="@($"{coach.Id}")" checked="@(Model.CoachId == coach.Id ? true : false)" />
                <label for="@($"{coach.Id}")">@coach.Name @coach.LastName - @coach.KindOfCoach</label>
            </div>
        }
    </div>

    <button type="submit">Edytuj indywidualny trening</button>
</form>

ClubManagement/Views/IndividualTraining/ShowIT.cshtml
@model Footballer;


<div>
    <h1>@Model.Name @Model.LastName - Lista Indywidualnych Treningów</h1>
    <p><a asp-controller="IndividualTraining" asp-action="showPlayers">Powrót do listy zawodników</a></p>
    <p><a asp-controller="IndividualTraining" asp-action="PrepareToAddIT" asp-route-id="@Model.Id">Dodaj trening</a></p>
    <p><a asp-controller="IndividualTraining" asp-action="RemoveAllIT" asp-route-id="@Model.Id">Usuń wszystko</a></p>
</div>
@if (TempData["Success"] != null)
{
    <div class="alert alert-success ">
        @TempData["Success"]
    </div>
}
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}
<div>
    @foreach(var obj in @Model.IndividualTrainings)
    {
        <div>
            @obj.DateOfTraining.ToString("dd-MM-yyyy")
            @obj.StartTraining.ToString("HH:mm") - @obj.EndTraining.ToString("HH:mm")
            | @obj.Title | Szczegóły |
            <a asp-controller="IndividualTraining" asp-action="PrepareToEditIT" asp-route-id="@obj.Id">Edytuj</a> |
            <a asp-controller="IndividualTraining" asp-action="RemoveIT" asp-route-id="@obj.Id">Usuń</a> 
            <div>
                @{
                    TimeSpan czas = obj.TimeOfTraining;
                    int godziny = czas.Hours;
                    int minuty = czas.Minutes;
                }
                <div>Typ treningu: @obj.Type</div>
                <div>Przewidywany czas: @godziny godz. @minuty min.</div>
                <div>Opis: @(obj.Description == null ? "Brak": obj.Description)</div>
                <div>Miejsce: @(obj.Place == null ? "Brak" : obj.Place)</div>
                <div>Trener: @(obj.CoachId == null ? "Brak trenera" : $"{obj.Coach.Name} {obj.Coach.LastName}")</div>
            </div>
        </div>
    }
</div>

ClubManagement/Views/IndividualTraining/ShowPlayers.cshtml
@model IEnumerable<Footballer>;

<div>
    <h1>Lista piłkarzy</h1>
    <p><a asp-controller="home" asp-action="index">Powrót</a></p>
</div>
@if (TempData["Success"] != null)
{
    <div class="alert alert-success ">
        @TempData["Success"]
    </div>
}
<div>
    @foreach (var obj in @Model)
    {
        <div>
            @obj.Name @obj.LastName -
            <a class="text-dark" asp-controller="IndividualTraining" asp-action="ShowIT" asp-route-id="@obj.Id">Indywidualne treningi</a>
        </div>
    }
</div>