ClubManagement/Models/Coach.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClubManagement.Models
{
    public class Coach
    {
        [Key]
        public int Id { get; set; }
        public int? AccountId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public string? Country { get; set; }
        public string? KindOfCoach { get; set; }
        public DateTime DateOfBirth { get; set; }
        // Coach 1-1 Account
        public Account Account { get; set; }
        // Coach 1-* IndividualTrainig
        public ICollection<IndividualTraining> IndividualTrainings { get; set; } = new List<IndividualTraining>();
        // Coach *-* GroupTraining
        public ICollection<GroupTraining> GroupTrainings { get; set; } = new List<GroupTraining>();
        // Coach *-* Match
        public ICollection<Match> Matches { get; set; } = new List<Match>();
    }
}

ClubManagement/Controllers/CoachController.cs
using ClubManagement.ApplicationDbContext;
using ClubManagement.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ClubManagement.Controllers
{
    public class CoachController : Controller
    {
        public readonly ClubDbContext _context;
        public CoachController(ClubDbContext context) 
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult ShowCoaches()
        {
            IEnumerable<Coach> coaches = _context.Coaches.ToList();

            return View(coaches);
        }

        // Dodawanie
        [HttpGet]
        //[Authorize(Policy = "AdminAccess")]
        public IActionResult PrepareToAddCoach(int? accountId) 
        {
            if (accountId == null)
                return RedirectToAction("register", "Account");

            ViewBag.AccountId = accountId;
            return View();
        }

        [HttpPost]
        //[Authorize(Policy = "AdminAccess")]
        public IActionResult AddCoach([FromForm]Coach coach)
        {
            // Walidacja wieku
            DateTime now = DateTime.Now;
            int coachAge = now.Year - coach.DateOfBirth.Year;
            DateTime givenDate = coach.DateOfBirth.AddYears(coachAge); 
            if (givenDate < now)
                coachAge--;

            if (coachAge < 18)
            {
                TempData["Alert"] = "Trener musi mieć co najmniej 18 lat";
                return RedirectToAction("PrepareToAddCoach", new { accountId = coach.AccountId });
            }
            // walidacja głównych trenerów
            string[] arrayOneHeads = { "headCoachFirstTeam", "headCoachReserves", "headCoachJuniors"};

            if(arrayOneHeads.Contains(coach.KindOfCoach))
            {
                var oneHeadCoach = _context.Coaches.Any(c => c.KindOfCoach == coach.KindOfCoach);
                if (oneHeadCoach)
                {
                    TempData["Alert"] = "Trener główny może być tylko jeden";
                    return RedirectToAction("PrepareToAddCoach", new { accountId = coach.AccountId });
                }
            }

            _context.Coaches.Add(coach);
            _context.SaveChanges();

            // Id do account
            var accountId = _context.Accounts.FirstOrDefault(a => a.Id == coach.AccountId);
            if (accountId == null)
                return NotFound();

            accountId.CoachId = coach.Id;
            _context.Accounts.Update(accountId);
            _context.SaveChanges();

            return RedirectToAction("ShowCoaches");
        }

        // Edytowanie
        [HttpGet]
        public IActionResult PrepareToEditCoach(int? id)
        {
            if (id == null || id == 0)
                return NotFound();

            var obj = _context.Coaches.FirstOrDefault(f => f.Id == id);

            if (obj == null)
                return NotFound();

            return View(obj);
        }

        [HttpPost]
        //[Authorize(Policy = "AdminAccess")]
        public IActionResult EditCoach([FromForm]Coach coach)
        {
            // Walidacja wieku
            DateTime now = DateTime.Now;
            int coachAge = now.Year - coach.DateOfBirth.Year;
            DateTime givenDate = coach.DateOfBirth.AddYears(coachAge);
            if (givenDate < now)
                coachAge--;

            if (coachAge < 18)
            {
                TempData["Alert"] = "Trener musi mieć co najmniej 18 lat";
                return RedirectToAction("PrepareToEditCoach", new { id = coach.Id });
            }

            // walidacja do roli trenera

            var coachToEdit = _context.Coaches.FirstOrDefault(x => x.Id == coach.Id);
            if (coachToEdit == null)
                return NotFound();

            string[] arrayOneHeads = { "headCoachFirstTeam", "headCoachReserves", "headCoachJuniors" };
            if (arrayOneHeads.Contains(coach.KindOfCoach))
            {
                var oneHeadCoach = _context.Coaches.Any(c => c.KindOfCoach == coach.KindOfCoach && c.Id != coach.Id);
                if (oneHeadCoach)
                {
                    TempData["Alert"] = "Trener główny może być tylko jeden";
                    return RedirectToAction("PrepareToEditCoach", new { id = coach.Id });
                }
            }

            coachToEdit.Name = coach.Name;
            coachToEdit.LastName = coach.LastName;
            coachToEdit.Country = coach.Country;
            coachToEdit.KindOfCoach = coach.KindOfCoach;
            coachToEdit.DateOfBirth = coach.DateOfBirth;

            _context.SaveChanges();

            TempData["Success"] = "Pomyślnie zaktualizowano trenera";
            return RedirectToAction("ShowCoaches");
        }

        // usuwanie
        public IActionResult RemoveCoach(int? id) 
        { 
            if (id == null)
                return NotFound("RemoveCoach - brak id");

            var coachToRemove = _context.Coaches.FirstOrDefault(c => c.Id == id);
            if (coachToRemove == null)
                return NotFound("RemoveCoach - brak obiektu trenera w bazie do usunięcia");

            _context.Coaches.Remove(coachToRemove);

            var accountToRemove = _context.Accounts.FirstOrDefault(a => a.Id == coachToRemove.AccountId);
            if (accountToRemove != null)
                _context.Accounts.Remove(accountToRemove);

            _context.SaveChanges();

            return RedirectToAction("ShowCoaches"); 
        }
    }
}

ClubManagement/Views/Coach/PrepareToAddCoach.cshtml
@model Coach;

<style>
    button, .fields {
        display: block;
    }
</style>
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}
<div>
    <h1>Dodanie nowego trenera</h1>
    <p><a asp-controller="Coach" asp-action="ShowCoaches">Powrót</a></p>
</div>
<form method="post" asp-action="AddCoach">
    <input type="hidden" asp-for="AccountId" value="@ViewBag.AccountId" />
    <div class="fields">
        <label asp-for="Name">Imię</label>
        <input type="text" asp-for="Name" />
    </div>
    <div class="fields">
        <label asp-for="LastName">Nazwisko</label>
        <input type="text" asp-for="LastName" />
    </div>
    <div class="fields">
        <label asp-for="Country">Kraj</label>
        <input type="text" asp-for="Country" />
    </div>
    <div class="fields">
        <label asp-for="KindOfCoach">Rodzaj trenera</label>
        <select asp-for="KindOfCoach">
            <option value="headCoachFirstTeam">Trener główny pierwszej drużyny</option>
            <option value="headCoachReserves">Trener główny rezerw</option>
            <option value="headCoachJuniors">Trener główny juniorów</option>
            <option value="goalkeepersCoach">Trener bramkarzy</option>
            <option value="assistantCoach">Asystent trenera</option>
            <option value="technicalCoach">Trener techniczny</option>
            <option value="physicalCoach">Trener fizyczny</option>
            <option value="tacticalCoach">Trener taktyczny</option>
@*             <option value="j">Trener indywidualny</option>
            <option value="k">Trener ds. psychologii sportu</option> *@
        </select>
    </div>
    <div class="fields">
        <label asp-for="DateOfBirth">Data urodzenia</label>
        <input type="date" asp-for="DateOfBirth" />
    </div>
    
    <button type="submit">
        Dodaj trenera
    </button>
</form>

ClubManagement/Views/Coach/PrepareToEditCoach.cshtml
@model Coach
<style>
    button, .fields {
        display: block;
    }
</style>
<div>
    <h1>Edycja trenera</h1>
    <p><a asp-controller="coach" asp-action="showCoaches">Powrót</a></p>
</div>
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}
<form method="post" asp-action="EditCoach">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="AccountId" />

    <div class="fields">
        <label asp-for="Name">Imię</label>
        <input type="text" asp-for="Name" />
    </div>
    <div class="fields">
        <label asp-for="LastName">Nazwisko</label>
        <input type="text" asp-for="LastName" />
    </div>
    <div class="fields">
        <label asp-for="Country">Kraj</label>
        <input type="text" asp-for="Country" />
    </div>
    <div class="fields">
        <label asp-for="KindOfCoach">Rodzaj trenera</label>
        <select asp-for="KindOfCoach">
            <option value="headCoachFirstTeam">Trener główny pierwszej drużyny</option>
            <option value="headCoachReserves">Trener główny rezerw</option>
            <option value="headCoachJuniors">Trener główny juniorów</option>
            <option value="goalkeepersCoach">Trener bramkarzy</option>
            <option value="assistantCoach">Asystent trenera</option>
            <option value="technicalCoach">Trener techniczny</option>
            <option value="physicalCoach">Trener fizyczny</option>
            <option value="tacticalCoach">Trener taktyczny</option>
        </select>
    </div>
    <div class="fields">
        <label asp-for="DateOfBirth">Data urodzenia</label>
        <input type="date" asp-for="DateOfBirth" />
    </div>

    <button type="submit">Edytuj Trenera</button>
</form>

ClubManagement/Views/Coach/ShowCoaches.cshtml
@model IEnumerable<Coach>

<style>
    .hidden {
        display: none;
    }
</style>

<div>
    <h1>Lista trenerów</h1>
    <p><a asp-controller="home" asp-action="index">Powrót</a></p>
</div>

@if (TempData["Success"] != null)
{
    <div class="alert alert-success ">
        @TempData["Success"]
    </div>
}
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger">
        @TempData["Alert"]
    </div>
}
<div>
    @foreach (var obj in @Model)
    {
        // Obliczanie wieku na podstawie daty urodzenia
        var age = DateTime.Today.Year - obj.DateOfBirth.Year;
        if (obj.DateOfBirth.Date > DateTime.Today.AddYears(-age))
            age--;

        <div>
            <p>@obj.Name @obj.LastName | @obj.DateOfBirth.ToString("dd-MM-yyyy") | Wiek: @age | @obj.Country | @obj.KindOfCoach</p>
            <p>
                <a class="text-dark" asp-controller="Coach" asp-action="PrepareToEditCoach" asp-route-id="@obj.Id">Edytuj trenera</a>
                <a class="text-dark" asp-controller="Coach" asp-action="RemoveCoach" asp-route-id="@obj.Id">Usuń trenera</a>
            </p>
        </div>
    }
</div>
<div>
    <a class="nav-link text-dark" asp-controller="Coach" asp-action="PrepareToAddCoach">Dodaj trenera</a>
</div>