ClubManagement/Models/Statistics.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClubManagement.Models
{
    public class Statistics
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Pełne mecze")]
        public int Match { get; set; }
        public int Minutes { get; set; }
        public int Goals { get; set; }
        public int Assists { get; set;}
        public int YellowCards { get; set; }
        public int RedCards { get; set; }
        // Footballer - Statistics | One to one
        public int? FootballerId { get; set; }
        public Footballer Footballer { get; set; }
        //public Footballer Footballer { get; set; } = null!;
    }
}

ClubManagement/Controllers/StatisticsController.cs
using ClubManagement.ApplicationDbContext;
using ClubManagement.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClubManagement.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly ClubDbContext _context;

        public StatisticsController(ClubDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult ShowStatistics()
        {
            IEnumerable<Footballer> statistics = _context.Footballers
                .Include(x => x.Statistics).ToList();

            return View(statistics);
        }

        // Edit Statistics
        [HttpGet]
        [Authorize(Policy = "AdminOrCoachAccess")]
        public IActionResult EditStatistics(int? id)
        {
            if(id == null || id == 0)
                return NotFound();

            var obj = _context.Footballers.Include(f => f.Statistics).FirstOrDefault(x => x.Id == id);

            if(obj == null)
                return NotFound();

            return View(obj);
        }

        [HttpPost]
        [Authorize(Policy = "AdminOrCoachAccess")]
        public IActionResult EditStatistics([FromForm]Statistics statistics)
        {
            var editedData = _context.Statistics.FirstOrDefault(s => s.Id == statistics.Id);
            if (editedData == null)
                return NotFound(statistics);

            // Warunek aby sprawdzić czy po odjęciu wartośc byłaby mniejsza niż zero
            // Jest tutaj + w drugim warunku bo przekazana wartość to -40 więc przy - by dodało 
            if(statistics.Minutes < 0 && editedData.Minutes + statistics.Minutes < 0)
            {
                TempData["Alert"] = $"Odjęta wartośc byłaby mniejsza niż zero | Aktualnie {editedData.Minutes} minut";
                return RedirectToAction("EditStatistics", new { id = editedData.Id });
            }
            else
            {
                editedData.Minutes += statistics.Minutes;
                int fullMatches = editedData.Minutes / 90;
                editedData.Match = fullMatches;
            }

            if(statistics.Goals < 0 && editedData.Goals + statistics.Goals < 0)
            {
                TempData["Alert"] = $"Odjęta wartośc byłaby mniejsza niż zero | Aktualnie {editedData.Goals} goli";
                return RedirectToAction("EditStatistics", new { id = editedData.Id });
            }
            else
                editedData.Goals += statistics.Goals;

            if (statistics.Assists < 0 && editedData.Assists + statistics.Assists < 0)
            {
                TempData["Alert"] = $"Odjęta wartośc byłaby mniejsza niż zero | Aktualnie {editedData.Assists} asyst";
                return RedirectToAction("EditStatistics", new { id = editedData.Id });
            }
            else
                editedData.Assists += statistics.Assists;

            if (statistics.YellowCards < 0 && editedData.YellowCards + statistics.YellowCards < 0)
            {
                TempData["Alert"] = $"Odjęta wartośc byłaby mniejsza niż zero | Aktualnie {editedData.YellowCards} żółtych kartek";
                return RedirectToAction("EditStatistics", new { id = editedData.Id });
            }
            else
                editedData.YellowCards += statistics.YellowCards;

            if (statistics.RedCards < 0 && editedData.RedCards + statistics.RedCards < 0)
            {
                TempData["Alert"] = $"Odjęta wartośc byłaby mniejsza niż zero | Aktualnie {editedData.RedCards} minut";
                return RedirectToAction("EditStatistics", new { id = editedData.Id });
            }
            else
                editedData.RedCards += statistics.RedCards;

            _context.SaveChanges();
            return RedirectToAction("ShowStatistics");
        }
    }
}

ClubManagement/Views/Statistics/EditStatistics.cshtml
@model Footballer;

<div>
    <h1>Edycja staystyk</h1>
    <p><a asp-controller="statistics" asp-action="ShowStatistics">Powrót</a></p>
</div>
@if (TempData["Alert"] != null)
{
    <div class="alert alert-danger ">
        @TempData["Alert"]
    </div>
}
<form method="post" asp-action="EditStatistics">
    <input type="hidden" asp-for="Statistics.Id" />
    <input type="hidden" asp-for="Statistics.FootballerId" />

    @* <div class="fields">
        <label asp-for="Statistics.Match">Mecze</label>
        <input type="number" asp-for="Statistics.Match" />
    </div> *@
    <div class="fields">
        <label asp-for="Statistics.Minutes">Minuty</label>
        <input type="text" asp-for="Statistics.Minutes" value="0" />
    </div>
    <div class="fields">
        <label asp-for="Statistics.Goals">Gole</label>
        <input type="text" asp-for="Statistics.Goals" value="0" />
    </div>
    <div class="fields">
        <label asp-for="Statistics.Assists">Asysty</label>
        <input type="text" asp-for="Statistics.Assists" value="0" />
    </div>
    <div class="fields">
        <label asp-for="Statistics.YellowCards">Źółte kartki</label>
        <input type="text" asp-for="Statistics.YellowCards" value="0" />
    </div>
    <div class="fields">
        <label asp-for="Statistics.RedCards">Czerwone kartki</label>
        <input type="text" asp-for="Statistics.RedCards" value="0" />
    </div>
  
    <button type="submit">Edytuj statystyki</button>
</form>

ClubManagement/Views/Statistics/ShowStatistics.cshtml
@model IEnumerable<Footballer>

<div>
    <h1>Statystyki piłkarzy</h1>
    <p><a asp-controller="home" asp-action="index">Powrót</a></p>
</div>
@if (TempData["Success"] != null)
{
    <div class="alert alert-success ">
        @TempData["Success"]
    </div>
}
<div>
    <ul>
        @foreach(var obj in Model)
        {
            <li>
                @obj.Name @obj.LastName
                <table>
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(n => n.Statistics.Match)</th>
                            <th>@Html.DisplayNameFor(n => n.Statistics.Minutes)</th>
                            <th>@Html.DisplayNameFor(n => n.Statistics.Goals)</th>
                            <th>@Html.DisplayNameFor(n => n.Statistics.Assists)</th>
                            <th>@Html.DisplayNameFor(n => n.Statistics.YellowCards)</th>
                            <th>@Html.DisplayNameFor(n => n.Statistics.RedCards)</th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td>@obj.Statistics.Match</td>
                            <td>@obj.Statistics.Minutes</td>
                            <td>@obj.Statistics.Goals</td>
                            <td>@obj.Statistics.Assists</td>
                            <td>@obj.Statistics.YellowCards</td>
                            <td>@obj.Statistics.RedCards</td>
                            <td>
                                <a class="nav-link text-dark" asp-controller="Statistics" asp-action="EditStatistics" asp-route-id="@obj.Id">Edytuj statystyki</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </li>
        }
    </ul>
</div>